"""Calibration evidence for the compatibility-confidence model.

Produces the two artifacts that prove the Platt-scaling layer earns its place:

  * Expected Calibration Error (ECE) **before vs after** Platt scaling.
  * A reliability diagram (docs/calibration_reliability.png) overlaying the naive baseline,
    the Platt-calibrated model, and the perfect-calibration diagonal.

"Before" = the naive confidence proxy the code falls back to when sklearn is unavailable
(``confidence = signal_coverage``). "After" = ``CalibrationModel.predict_confidence`` (Platt-scaled
logistic regression). The held-out test set is generated by the *same* latent process used to fit
the model (``app.calibration``), but with a different seed, so the comparison is honest.

Run:  cd apps/backend && uv run python ../../scripts/calibration_evidence.py
"""

from __future__ import annotations

import sys
from pathlib import Path

THIS = Path(__file__).resolve()
BACKEND = THIS.parents[1] / "apps" / "backend"
if (BACKEND / "app").exists():
    sys.path.insert(0, str(BACKEND))

import numpy as np  # noqa: E402
import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from app.calibration import CalibrationConfig, CalibrationModel  # noqa: E402

N_TEST = 8000
TEST_SEED = 2024
N_BINS = 10


def generate_labeled_test_set(n: int, seed: int, n_dims: int = 8):
    """Replicate app.calibration's latent process to get (scores, coverage, label) triples.

    Mirrors CalibrationModel.from_synthetic_data so the held-out set is drawn from the same
    distribution the model was trained against (different seed → genuine generalization check).
    """
    rng = np.random.default_rng(seed)
    scores_list, coverage_list, labels = [], [], []
    for _ in range(n):
        coverage = rng.uniform(0.1, 1.0)
        observed_mask = rng.uniform(0, 1, n_dims) < coverage
        latent = rng.normal(0.0, 1.0)
        noise = rng.normal(0.0, max(0.15, 1.0 - coverage), n_dims)
        scores = np.clip(1 / (1 + np.exp(-(latent + noise))), 0.0, 1.0)
        scores[~observed_mask] = 0.5
        std_score = np.std(scores)
        mean_score = np.mean(scores)
        certainty = (
            2.4 * coverage
            + 1.6 / (1.0 + std_score)
            + 0.5 * abs(mean_score - 0.5)
            - 1.8 * (1.0 - coverage) * abs(mean_score - 0.5)
            + rng.normal(0.0, 0.35)
        )
        scores_list.append(scores)
        coverage_list.append(coverage)
        labels.append(rng.binomial(1, 1 / (1 + np.exp(-certainty))))
    return scores_list, np.asarray(coverage_list), np.asarray(labels)


def expected_calibration_error(probs: np.ndarray, labels: np.ndarray, bins: int = N_BINS) -> float:
    edges = np.linspace(0.0, 1.0, bins + 1)
    n = len(probs)
    ece = 0.0
    for i in range(bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (probs >= lo) & (probs <= hi if i == bins - 1 else probs < hi)
        if mask.sum() == 0:
            continue
        conf = probs[mask].mean()
        acc = labels[mask].mean()
        ece += (mask.sum() / n) * abs(conf - acc)
    return float(ece)


def reliability_points(probs: np.ndarray, labels: np.ndarray, bins: int = N_BINS):
    edges = np.linspace(0.0, 1.0, bins + 1)
    xs, ys = [], []
    for i in range(bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (probs >= lo) & (probs <= hi if i == bins - 1 else probs < hi)
        if mask.sum() == 0:
            continue
        xs.append(float(probs[mask].mean()))
        ys.append(float(labels[mask].mean()))
    return xs, ys


def main() -> None:
    model = CalibrationModel.from_synthetic_data(CalibrationConfig())
    scores_list, coverage, labels = generate_labeled_test_set(N_TEST, TEST_SEED)

    naive = coverage.copy()  # the code's fallback confidence proxy
    calibrated = np.array([
        model.predict_confidence(s, c) for s, c in zip(scores_list, coverage)
    ])

    ece_naive = expected_calibration_error(naive, labels)
    ece_cal = expected_calibration_error(calibrated, labels)

    nx, ny = reliability_points(naive, labels)
    cx, cy = reliability_points(calibrated, labels)

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.plot([0, 1], [0, 1], "--", color="#888", label="Perfect calibration")
    ax.plot(nx, ny, "o-", color="#d9772e", label=f"Naive (coverage)  ECE={ece_naive:.3f}")
    ax.plot(cx, cy, "s-", color="#2e7dd9", label=f"Platt-calibrated   ECE={ece_cal:.3f}")
    ax.set_xlabel("Predicted confidence")
    ax.set_ylabel("Observed reliability (fraction correct)")
    ax.set_title("Reliability Diagram — Compatibility Confidence")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(alpha=0.3)
    fig.tight_layout()

    docs = THIS.parents[1] / "docs"
    docs.mkdir(exist_ok=True)
    png = docs / "calibration_reliability.png"
    fig.savefig(png, dpi=130)

    md = docs / "calibration_evidence.md"
    improvement = (ece_naive - ece_cal) / ece_naive * 100 if ece_naive else 0.0
    with open(md, "w", encoding="utf-8") as fh:
        fh.write("# Calibration Evidence — Confidence Model\n\n")
        fh.write(f"Held-out test set: **{N_TEST}** synthetic samples (seed {TEST_SEED}), "
                 f"{N_BINS}-bin ECE. Reproduce: `uv run python ../../scripts/calibration_evidence.py`.\n\n")
        fh.write("| confidence source | Expected Calibration Error (ECE) |\n|---|---|\n")
        fh.write(f"| Naive (signal coverage) | {ece_naive:.4f} |\n")
        fh.write(f"| Platt-scaled (logistic regression) | {ece_cal:.4f} |\n\n")
        fh.write(f"**Platt scaling reduces ECE by {improvement:.0f}%** "
                 f"({ece_naive:.3f} → {ece_cal:.3f}).\n\n")
        fh.write("![Reliability diagram](calibration_reliability.png)\n\n")
        fh.write("**Interpretation:** the naive coverage proxy is over/under-confident — its curve "
                 "departs from the diagonal. The Platt-scaled model's points sit closer to the "
                 "diagonal, i.e. when it says 70% it is right ~70% of the time. ECE quantifies that "
                 "gap; lower is better.\n")

    print(f"ECE naive      = {ece_naive:.4f}")
    print(f"ECE calibrated = {ece_cal:.4f}")
    print(f"Improvement    = {improvement:.0f}%")
    print(f"Wrote {png}\nWrote {md}")


if __name__ == "__main__":
    main()
